# === Application Launchers ===
bind = SUPER, space, exec, dms ipc call spotlight toggle
bind = SUPER SHIFT, V, exec, dms ipc call clipboard toggle
bind = SUPER, M, exec, dms ipc call processlist focusOrToggle
bind = SUPER, comma, exec, dms ipc call settings focusOrToggle
bind = SUPER, N, exec, dms ipc call notifications toggle
bind = SUPER SHIFT, N, exec, dms ipc call notepad toggle
bind = SUPER, Y, exec, dms ipc call dankdash wallpaper
bind = ALT, TAB, exec, dms ipc call hypr toggleOverview
bind = SUPER SHIFT, E, exec, dms ipc call powermenu toggle

# bindd = Super+Shift, E, , global, dms ipc call powermenu toggle # Toggle session menu
# bind = Super, Space, global, dms ipc call spotlight toggle # Toggle overview/launcher
# bind = Alt, Tab, global, dms ipc call hypr toggleOverview # Toggle overview/launcher
# bindd = Super+Shift, V, , global, dms ipc call clipboard toggle # Clipboard history
# bindd = Super, Y, , global, dms ipc call dankdash wallpaper # Toggle wallpaper picker

# === Cheat sheet
bind = SUPER SHIFT, Slash, exec, dms ipc call keybinds toggle hyprland

# === Security ===
bind = SUPER ALT, L, exec, dms ipc call lock lock
# bind = SUPER SHIFT, E, exit
bind = CTRL ALT, Delete, exec, dms ipc call processlist focusOrToggle

# === Audio Controls ===
bindel = , XF86AudioRaiseVolume, exec, dms ipc call audio increment 3
bindel = , XF86AudioLowerVolume, exec, dms ipc call audio decrement 3
bindl = , XF86AudioMute, exec, dms ipc call audio mute
bindl = , XF86AudioMicMute, exec, dms ipc call audio micmute
bindl = , XF86AudioPause, exec, dms ipc call mpris playPause
bindl = , XF86AudioPlay, exec, dms ipc call mpris playPause
bindl = , XF86AudioPrev, exec, dms ipc call mpris previous
bindl = , XF86AudioNext, exec, dms ipc call mpris next
bindel = CTRL, XF86AudioRaiseVolume, exec, dms ipc call mpris increment 3
bindel = CTRL, XF86AudioLowerVolume, exec, dms ipc call mpris decrement 3

# === Brightness Controls ===
bindel = , XF86MonBrightnessUp, exec, dms ipc call brightness increment 5 ""
bindel = , XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5 ""

# # === Workspace Management ===
# bind = CTRL SHIFT, R, exec, dms ipc call workspace-rename open

# === Screenshots ===
bind = , Print, exec, dms screenshot
bind = CTRL, Print, exec, dms screenshot full
bind = ALT, Print, exec, dms screenshot window





