# ################################### Applications ###################################

# These absolutely need to be on top, or they won't work consistently
bindnit = , Escape, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bindnit = , Escape, global, quickshell:cheatsheetClose # [hidden]
bindnit = , Escape, global, quickshell:mediaControlsClose # [hidden]
bind = Super, mouse:272, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:273, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:274, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:275, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:276, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse:277, global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse_up,  global, quickshell:overviewToggleReleaseInterrupt # [hidden]
bind = Super, mouse_down,global, quickshell:overviewToggleReleaseInterrupt # [hidden]

bindit = ,Super_L, global, quickshell:workspaceNumber # [hidden]

bind = ,Print, exec, qs -p ~/.config/quickshell/screenshot.qml # [hidden]

#!
##! Shell
bind = Super, Space, global, quickshell:overviewToggleRelease # Toggle overview/launcher
bind = Alt, Tab, global, quickshell:overviewToggleRelease # Toggle overview/launcher
bindd = Super, Period, Emoji >> clipboard, global, quickshell:overviewEmojiToggle # Emoji picker
bindd = Super+Shift, V, Clipboard history >> clipboard, global, quickshell:overviewClipboardToggle # Clipboard history

bindd = Super, Y, Toggle bar, global, quickshell:barToggle # Toggle bar

# Media
bindl= ,XF86AudioNext, exec, playerctl next # [hidden]
bindl= ,XF86AudioPrevious, exec, playerctl previous # [hidden]
bindl= ,XF86AudioPlay, exec, playerctl play-pause # [hidden]

# bindl= ,XF86AudioRaiseVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --increase 5 || amixer -q -D pulse sset Master 5%+
# bindl= ,XF86AudioLowerVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --decrease 5 || amixer -q -D pulse sset Master 5%-
bindl= ,XF86AudioRaiseVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05+ # [hidden]
bindl= ,XF86AudioLowerVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05- # [hidden]
bindl= ,XF86AudioMute, exec, wpctl set-mute "@DEFAULT_AUDIO_SINK@" toggle # [hidden]

# Screenshots
bind = ,Print, exec, pgrep qs || hyprshot --freeze --clipboard-only -m region # Screenshot region (clipboard)
bind = Shift,Print, exec, hyprshot --freeze --clipboard-only -m window # Screenshot window (clipboard)
bind = Super, Print, exec, hyprshot --freeze -m region # Screenshot region
bind = Super+Shift, Print, exec, hyprshot --freeze -m window # Screenshot window

##! Panels
bindd = Super, b, Toggle left sidebar, global, quickshell:sidebarLeftToggle # Toggle left sidebar
bindd = Super, n, Toggle right sidebar, global, quickshell:sidebarRightToggle # Toggle right sidebar
bindd = Super, Slash, Toggle cheatsheet, global, quickshell:cheatsheetToggle # Toggle cheatsheet
bindd = Super, m, Toggle media controls, global, quickshell:mediaControlsToggle # Toggle media controls
bindd = Super+Shift, E, Toggle session menu, global, quickshell:sessionToggle # Toggle session menu

bind = Super+Alt, B, global, quickshell:sidebarLeftToggleDetach # [hidden]


