apps:
  browser: vivaldi --ozone-platform-hint=wayland
  file_explorer: nemo
  music_player: youtube-music
  pdf_viewer: sioyek
  sound_manager: pavucontrol
  terminal: kitty
backup:
  - ignore-patterns:
      - \.CondaPkg
      - target
      - \.?v?env
      - \.cache
      - node_modules
      - kitti-dataset
      - build
    source: /mnt/DiscoExterno/_Codes
    destination: drive-usp:Codes
    action: copy
  - destination: drive-usp:PDFs
    action: copy
    source: /mnt/DiscoExterno/_Arquivos/PDFs
  - source: /mnt/DiscoExterno/ObsidianVaults/USP
    destination: drive-usp:Obsidian/USP
    action: copy
import:
  - ./chezmoi.yaml
  - ./pkgs.yaml
  - ./hyprland.yaml
  - ./bspwm.yaml
