apps:
  browser: vivaldi --ozone-platform-hint=wayland
  file_explorer: nemo
  music_player: youtube-music
  pdf_viewer: sioyek
  sound_manager: pavucontrol
  terminal: kitty
backup:
- action: copy
  destination: drive-usp:PDFs
  source: /mnt/DiscoExterno/_Arquivos/PDFs
- action: copy
  destination: drive-usp:Obsidian/USP
  source: /mnt/DiscoExterno/ObsidianVaults/USP
- action: copy
  destination: drive-usp:Codes
  ignore-patterns:
  - \.?v?env
  - node_modules
  - target
  - build
  - \.CondaPkg
  - kitti-dataset
  - \.cache
  source: /mnt/DiscoExterno/_Codes
import:
- ./chezmoi.yaml
- ./pkgs.yaml
- ./hyprland.yaml
- ./bspwm.yaml
