#!/bin/sh 


if [ -z "$1" ] || [ "$1" = "--list" ]; then
	archdots settings '.apps'
	exit
elif [ "$1" = "--query" ] && [ -n "$2" ]; then
	key="$(archdots settings '.apps|keys.[]'|rg "$2")"
	archdots settings ".apps.$key" 2> /dev/null

elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	cat << EOF
bsplaunch - Launch apps defined in $BSPSETTINGS

Usage:
  bsplaunch
  bsplaunch [APP]
  bsplaunch -h | --help

APP             $(archdots settings '.apps|keys.[]'|rg -U '\n(\w)' -r '|$1')

Flags:
  --list        show all available apps
  --help | -h   show this help text
  --query       find apps by query
EOF
exit
fi

app_name=$(archdots settings ".apps.$1" 2> /dev/null)

if [ "$2" = "-r" ]; then
	printf "%s" "$app_name"
else
	$app_name
fi


