#!/bin/env bash

# usage
# bspscripts [restart] [scripts|programs]
#
# [restart]            kill and launch 
# [scripts|programs]   only afect selected type

myscripts=(
    "$BSPDIR/color-border-mode.sh"
    "$BSPDIR/fix-polybar-fullscreen.sh"
    "lockscreen.sh disable"
)

myprograms=(
    "fcitx5 -d"
    "dunst"
    "nm-applet"
    "picom"
    "evrouter /dev/input/by-id/usb-18f8_USB_GAMING_MOUSE-event-mouse /dev/input/by-id/usb-SONiX_USB_DEVICE-event-kbd"
    "greenclip daemon"
    "bspdragwin.py --daemon"
    "eww daemon --restart"
    "jgmenu --hide-on-startup"
    "bspswallow"
    "unclutter --timeout 10 --exclude-root"
    "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
)

# refresh xmopmap mappings
xmodmap ~/.config/X11/xmodmap

bash $TOOLS/setup-monitors.sh

if [ -n "$1" ] && [ "$1" != "restart" ]; then
    2=$1
fi

if [ -z "$2" ] || [ "$2" = "scripts" ]; then
    for script in "${myscripts[@]}"; do
        unset script_arguments

        script_arguments=(${script[@]})

        script_path="${script_arguments[0]}"
        script_basename="$(basename "$script_path")"

        script_arguments=$(echo "${script_arguments[@]:1}")

        if [ -n "$script_arguments" ];then
            script_command="$script_path $script_arguments"
        else
            script_command="$script_path"
        fi

        if [ "$1" = "restart" ];then
            echo "$script_command"
            pgrep -f "$script_basename"|xargs -i kill {};sleep 1 && bash $script_command &
        else
            pgrep -f "$script_basename" > /dev/null || bash $script_command &
        fi
    done
fi

if [ -z "$2" ] || [ "$2" = "programs" ]; then
    for program in "${myprograms[@]}"; do
        unset program_arguments

        program_arguments=(${program[@]})

        program_path="${program_arguments[0]}"
        program_basename="$(basename "$program_path")"

        program_arguments=$(echo "${program_arguments[@]:1}")

        if [ -n "$program_arguments" ];then
            program_command="$program_path $program_arguments"
        else
            program_command="$program_path"
        fi

        if [ "$1" = "restart" ];then
            pgrep -x "$program_basename"|xargs -i kill {};sleep 1 && $program_command &
        else
            pgrep -x "$program_basename" > /dev/null || $program_command &
        fi
    done
fi

