#!/bin/sh 


if [ -z "$1" ] || [ "$1" = "--list" ]; then
	jq .apps "$BSPDIR/settings.json"
	exit
elif [ "$1" = "--query" ] && [ -n "$2" ]; then
	key="$(jq -r '.apps|keys.[]' $BSPDIR/settings.json|rg "$2")"
	jq -r ".apps.$key" "$BSPDIR/settings.json" 2> /dev/null

elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	cat << EOF
bsplaunch - Launch apps defined in ~/.config/bspwm/settings.json

Usage:
  bsplaunch
  bsplaunch [APP]
  bsplaunch -h | --help

APP             $(jq -r '.apps|keys.[]' $BSPDIR/settings.json|rg -U '\n(\w)' -r '|$1')

Flags:
  --list        show all available apps
  --help | -h   show this help text
  --query       find apps by query
EOF
exit
fi

app_name=$(jq -r ".apps.$1" "$BSPDIR/settings.json" 2> /dev/null)

if [ "$2" = "-r" ]; then
	printf "%s" "$app_name"
else
	$app_name
fi


