#!/usr/bin/bash
function print_title () { echo -e "\033[0;36m::\033[0m $@"; }
# always
print_title 'cycle-audio-devices.nu --refresh||true'; cycle-audio-devices.nu --refresh||true
print_title '$TOOLS/setup-monitors.sh'; $TOOLS/setup-monitors.sh
print_title 'xmodmap $HOME/.config/X11/xmodmap'; xmodmap $HOME/.config/X11/xmodmap
print_title 'rm /tmp/.evrouter:0||true'; rm /tmp/.evrouter:0||true

# scripts
pgrep -f "$HOME/.config/eww/scripts/music_helper.sh --cover_daemon" >/dev/null || (print_title '$HOME/.config/eww/scripts/music_helper.sh --cover_daemon'; $HOME/.config/eww/scripts/music_helper.sh --cover_daemon) &pgrep -f "$BSPDIR/color-border-mode.sh" >/dev/null || (print_title '$BSPDIR/color-border-mode.sh'; $BSPDIR/color-border-mode.sh) &pgrep -f "$BSPDIR/fix-polybar-fullscreen.sh" >/dev/null || (print_title '$BSPDIR/fix-polybar-fullscreen.sh'; $BSPDIR/fix-polybar-fullscreen.sh) &
# programs
pgrep -x "syncthing" >/dev/null || (print_title 'syncthing serve --no-browser --logfile=default'; syncthing serve --no-browser --logfile=default) &pgrep -x "picom" >/dev/null || (print_title 'picom'; picom) &pgrep -x "nm-applet" >/dev/null || (print_title 'nm-applet'; nm-applet) &pgrep -x "unclutter" >/dev/null || (print_title 'unclutter --timeout 10 --exclude-root'; unclutter --timeout 10 --exclude-root) &pgrep -x "jgmenu" >/dev/null || (print_title 'jgmenu --hide-on-startup'; jgmenu --hide-on-startup) &pgrep -x "bspswallow" >/dev/null || (print_title 'bspswallow'; bspswallow) &pgrep -x "fcitx5" >/dev/null || (print_title 'fcitx5 -d'; fcitx5 -d) &pgrep -x "polkit-gnome-authentication-agent-1" >/dev/null || (print_title '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1'; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1) &pgrep -x "bspdragwin.py" >/dev/null || (print_title 'bspdragwin.py --daemon'; bspdragwin.py --daemon) &pgrep -x "greenclip" >/dev/null || (print_title 'greenclip daemon'; greenclip daemon) &pgrep -x "dunst" >/dev/null || (print_title 'dunst'; dunst) &pgrep -x "syncthing-gtk" >/dev/null || (print_title 'syncthing-gtk --minimized'; syncthing-gtk --minimized) &pgrep -x "evrouter" >/dev/null || (print_title 'evrouter --config $HOME/.config/evrouter/.evrouterrc /dev/input/by-id/usb-18f8_USB_GAMING_MOUSE-event-mouse /dev/input/by-id/usb-SONiX_USB_DEVICE-event-kbd'; evrouter --config $HOME/.config/evrouter/.evrouterrc /dev/input/by-id/usb-18f8_USB_GAMING_MOUSE-event-mouse /dev/input/by-id/usb-SONiX_USB_DEVICE-event-kbd) &pgrep -x "eww" >/dev/null || (print_title 'eww daemon --restart'; eww daemon --restart) &
