# ################################### Applications ###################################
# bind = Super, Return, exec, dots launch terminal
#!
##! Programs
bind = Super, Return, exec, kitty # Launch Terminal
bind = Super+Shift, n, exec, dots launch file_explorer # Launch File Explorer
bind = Super+Shift, Return, exec, dots launch browser # Launch Web Browser

##! Scratchpad
bind = Super+Ctrl, x, exec, pypr toggle filemanager # File Explorer
bind = ,XF86Search, exec, pypr toggle pavucontrol # Sound Manager
bind = Super+Ctrl, Z, exec, pypr toggle music # Music Player
bind = Super+Shift, Z, exec, pypr toggle kitty # Terminal
bind = Super+Ctrl, backslash, exec, pypr toggle qalculate # Calculator

##! Misc
# Screenshots
bind = ,Print, exec, hyprshot --freeze --clipboard-only -m region # Screenshot region (clipboard)
bind = Shift,Print, exec, hyprshot --freeze --clipboard-only -m window # Screenshot window (clipboard)
bind = Super, Print, exec, hyprshot --freeze -m region # Screenshot region
bind = Super+Shift, Print, exec, hyprshot --freeze -m window # Screenshot window

# Media
bindl= ,XF86AudioNext, exec, playerctl next # [hidden]
bindl= ,XF86AudioPrevious, exec, playerctl previous # [hidden]
bindl= ,XF86AudioPlay, exec, playerctl play-pause # [hidden]

# bindl= ,XF86AudioRaiseVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --increase 5 || amixer -q -D pulse sset Master 5%+
# bindl= ,XF86AudioLowerVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --decrease 5 || amixer -q -D pulse sset Master 5%-
bindl= ,XF86AudioRaiseVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05+ # [hidden]
bindl= ,XF86AudioLowerVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05- # [hidden]
bindl= ,XF86AudioMute, exec, wpctl set-mute "@DEFAULT_AUDIO_SINK@" toggle # [hidden]

bindl= ,XF86Calculator, exec, ~/.scripts/tools/cycle-audio-devices.nu # Cycle audio devices
bindl= Shift,XF86Calculator, exec, ~/.scripts/tools/cycle-audio-devices.nu port # Cycle audio ports

# ################################### Rofi ###################################

# All Rofi scripts
bind = Super, C, exec, ~/.scripts/rofi-scripts/rofi-all.sh # Misc scripts
bind = Super+Ctrl, Space, exec, ~/.scripts/rofi-scripts/rofi-zoxide.sh # Zoxide

# App launcher
bind = Super, Space, exec, qs ipc call TEST_ALIVE || rofi -show drun # [hidden]

# Power Menu
bind = Super+Shift, E, exec, qs ipc call TEST_ALIVE || rofi -show power-menu -modi "power-menu:~/.local/bin/rofi-power-menu --choices=lockscreen/shutdown/reboot/logout/suspend/hibernate" # [hidden]

# ##################################### Hyprland #####################################
##! Hyprland
bind = Super+Alt, R, exec, hyprctl reload # Reload
bind = Super+Shift+Alt, R, exec, dots autostart hyprland_programs --restart # Restart daemons

# Move/resize windows with Super + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow # [hidden]
bindm = Super, mouse:273, resizewindow # [hidden]
