# ################################### Applications ###################################
# bind = Super, Return, exec, dots launch terminal
bind = Super, Return, exec, kitty
bind = Super+Shift, n, exec, dots launch file_explorer
bind = Super+Ctrl, x, exec, pypr toggle filemanager
bind = Super+Shift, Return, exec, dots launch browser
bind = ,XF86Search, exec, pypr toggle pavucontrol
bind = Super+Ctrl, Z, exec, pypr toggle music
bind = Super+Shift, Z, exec, pypr toggle kitty
bind = Super+Ctrl, backslash, exec, pypr toggle qalculate

# Screenshots
bind = ,Print, exec, hyprshot --clipboard-only -m region
bind = Shift,Print, exec, hyprshot --clipboard-only -m window
bind = Super, Print, exec, hyprshot -m region
bind = Super+Shift, Print, exec, hyprshot -m window

# Actions
bind = Super+Shift, Q, killactive,

# Media
bindl= ,XF86AudioNext, exec, playerctl next
bindl= ,XF86AudioPrevious, exec, playerctl previous
bindl= ,XF86AudioPlay, exec, playerctl play-pause

bindl= ,XF86Calculator, exec, ~/.scripts/tools/cycle-audio-devices.nu
bindl= Shift,XF86Calculator, exec, ~/.scripts/tools/cycle-audio-devices.nu port


# bindl= ,XF86AudioRaiseVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --increase 5 || amixer -q -D pulse sset Master 5%+
# bindl= ,XF86AudioLowerVolume, exec, pamixer --sink $(cycle-audio-devices.nu sink --active) --decrease 5 || amixer -q -D pulse sset Master 5%-
bindl= ,XF86AudioRaiseVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05+
bindl= ,XF86AudioLowerVolume, exec, wpctl set-volume "@DEFAULT_AUDIO_SINK@" 0.05-
bindl= ,XF86AudioMute, exec, wpctl set-mute "@DEFAULT_AUDIO_SINK@" toggle


# ################################### Rofi ###################################

# App launcher
bind = Super, Space, exec, qs ipc call TEST_ALIVE || rofi -show drun

# Power Menu
bind = Super+Shift, E, exec, qs ipc call TEST_ALIVE || rofi -show power-menu -modi "power-menu:~/.local/bin/rofi-power-menu --choices=lockscreen/shutdown/reboot/logout/suspend/hibernate"

# ##################################### Hyprland #####################################
bind = Super+Alt, R, exec, hyprctl reload
bind = Super+Shift+Alt, R, exec, dots autostart hyprland_programs --restart

# Move/resize windows with Super + LMB/RMB and dragging
bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
