# Jump cursor to a position
bind=Super+Shift,P,exec, wl-kbptr -o modes=tile -c ~/.config/wl_kbptr/config.toml
bind=Super,P,exec, wl-kbptr -o modes=tile,split,click -c ~/.config/wl_kbptr/config.toml


