exec = crontab -l
exec = /opt/urserver/urserver-stop;/opt/urserver/urserver-start --no-manager --no-notify &
exec = killall waybar; pgrep zcroll|xargs kill -9;waybar

# Wallpaper
exec-once = swaybg -i ~/.config/bspwm/wallpapers/hell3.png

# Input method
exec-once = fcitx5 -d &

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 20

exec = archdots autostart; notify-send archdots autostart
exec-once = archdots alternate_config auto

