# # # Using systemd to autostart
# # Statusbar
# # exec-once = systemctl --user start hyprpanel
# # exec-once = systemctl --user start quickshell
# 
# # Wallpaper
# # exec-once = systemctl --user start hyprpaper && ~/.config/hypr/hyprpaper/load_generated.sh

# Idle management
exec-once = systemctl --user start hypridle


# pypr plugins
exec-once = pypr

# Polkit agent
exec-once = systemctl --user start hyprpolkitagent

# archdots
exec-once = dots health configure autostart_scripts_export
exec = dots autostart hyprland_programs &>/tmp/autostart.log

# darkmode
exec = gsettings set org.gnome.desktop.interface gtk-theme "TokyoNight"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
