# ################################### Applications ###################################


# ################################### Rofi ###################################

# All Rofi scripts
bind = Super, C, exec, ~/.scripts/rofi-scripts/rofi-all.sh

# Zoxide
bind = Super+Ctrl, Space, exec, ~/.scripts/rofi-scripts/rofi-zoxide.sh 

# Clipboard Menu
bind = Super+Shift, v, exec, rofi -modi "clipboard:~/.scripts/bin/greenclip print" -show clipboard -run-command '{cmd}'

# ########################### Keybinds for Hyprland ############################

bind = Super, s, togglefloating, 

# Swap windows
bind = Super+Shift, h, exec, hyprnavi l --swap
bind = Super+Shift, l, exec, hyprnavi r --swap
bind = Super+Shift, k, swapwindow, u
bind = Super+Shift, j, swapwindow, d

# Move windows
bind = Super+Shift, Left, movewindow, l
bind = Super+Shift, Right, movewindow, r
bind = Super+Shift, Up, movewindow, u
bind = Super+Shift, Down, movewindow, d

bind = Super, w, togglegroup, 

# Focus Windows
# bind = Super, h, hycov:movefocus, leftcross
# bind = Super, l, hycov:movefocus, rightcross
# bind = Super, k, hycov:movefocus, upcross
# bind = Super, j, hycov:movefocus, downcross
bind = Super, h, movefocus, l
bind = Super, l, movefocus, r
bind = Super, k, movefocus, u
bind = Super, k, changegroupactive, f
bind = Super, j, movefocus, d
bind = Super, j, changegroupactive, b

bind = Super, Left, movefocus, l
bind = Super, Right, movefocus, r
bind = Super, Up, movefocus, u
bind = Super, Down, movefocus, d

# Focus Next/Previous Workspace
bind = Super, Tab, workspace, m+1
bind = Super+Shift, Tab, workspace, m-1
bind = Super+Alt, Tab, movetoworkspace, m+1
bind = Super+Alt+Shift, Tab, movetoworkspace, m-1

# Swap monitors
bind = Super+Shift+Ctrl, l, exec, hyprctl dispatch swapactiveworkspaces '0 1' && hyprctl dispatch focusmonitor r
bind = Super+Shift+Ctrl, h, exec, hyprctl dispatch swapactiveworkspaces '0 1' && hyprctl dispatch focusmonitor l

# Fullscreen
bind = Super, F, fullscreen, 0
bind = Super, A, fullscreenstate, 1 -1


# Focus next empty workspace
bind = Super, Apostrophe, workspace, emptym

# Move window to the next empty workspace
bind = Super+Alt, Apostrophe, movetoworkspace, emptym

# Move window to the next empty workspace without focusing it
bind = Super+Shift, Apostrophe, movetoworkspacesilent, emptym

# Focus next monitor
bind = Super, U, focusmonitor, +1

# Focus Workspace
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# Move window to workspace Super + Alt + [0-9] 
bind = Super+Alt, 1, movetoworkspace, 1
bind = Super+Alt, 2, movetoworkspace, 2
bind = Super+Alt, 3, movetoworkspace, 3
bind = Super+Alt, 4, movetoworkspace, 4
bind = Super+Alt, 5, movetoworkspace, 5
bind = Super+Alt, 6, movetoworkspace, 6
bind = Super+Alt, 7, movetoworkspace, 7
bind = Super+Alt, 8, movetoworkspace, 8
bind = Super+Alt, 9, movetoworkspace, 9
bind = Super+Alt, 0, movetoworkspace, 10

# Move window to workspace without focusing Super + Shift + [0-9] 
bind = Super+Shift, 1, movetoworkspacesilent, 1
bind = Super+Shift, 2, movetoworkspacesilent, 2
bind = Super+Shift, 3, movetoworkspacesilent, 3
bind = Super+Shift, 4, movetoworkspacesilent, 4
bind = Super+Shift, 5, movetoworkspacesilent, 5
bind = Super+Shift, 6, movetoworkspacesilent, 6
bind = Super+Shift, 7, movetoworkspacesilent, 7
bind = Super+Shift, 8, movetoworkspacesilent, 8
bind = Super+Shift, 9, movetoworkspacesilent, 9
bind = Super+Shift, 0, movetoworkspacesilent, 10

