# When entering overview mode, you can use left-button to jump, right-button to kill or use keybind

exec-once = sleep 2 && hyprpm reload -n

# source=~/.config/hypr/plugins/hyprscroller.conf
source=~/.config/hypr/plugins/dynamic-cursors.conf
# source=~/.config/hypr/plugins/hyprexpo.conf
source=~/.config/hypr/plugins/hyprspace.conf
