[pyprland]
plugins = [
    "scratchpads",
    "shift_monitors"
]

[scratchpads.kitty]
animation = "fromBottom"
command = "kitty --class kitty-scratchpad"
class = "kitty-scratchpad"
size = "75% 60%"
preserve_aspect = true
# max_size = "1920px 100%"
# margin = 50

[scratchpads.music]
animation = "fromBottom"
command = "youtube-music"
class = "com.github.th_ch.youtube_music"
size = "70% 75%"
preserve_aspect = true
margin = 150

[scratchpads.filemanager]
animation = "fromBottom"
command = "nemo --class __float__Nemo"
class = "__float__Nemo"
size = "70% 75%"
preserve_aspect = true
margin = 150
