[pyprland]
plugins = [
    "scratchpads",
    "shift_monitors"
]

[scratchpads.kitty]
# animation = "fromBottom"
animation = ""
command = "kitty --class kitty-scratchpad"
class = "kitty-scratchpad"
size = "75% 60%"
preserve_aspect = true
# max_size = "1920px 100%"
# margin = 50


[scratchpads.music]
animation = ""
command = "youtube-music --ozone-platform-hint=wayland --enable-wayland-ime --wayland-text-input-version=3"
class = "com.github.th_ch.youtube_music"
size = "70% 75%"
preserve_aspect = true
margin = 150

[scratchpads.qalculate]
# animation = "fromBottom"
animation = ""
command = "qalculate-gtk"
class = "qalculate-gtk"
size = "20% 60%"
preserve_aspect = true
margin = 150

[scratchpads.filemanager]
# animation = "fromBottom"
animation = ""
command = "nemo --class __float__Nemo"
class = "__float__Nemo"
size = "70% 75%"
preserve_aspect = true
margin = 150

[scratchpads.pavucontrol]
# animation = "fromBottom"
animation = ""
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "70% 75%"
preserve_aspect = true
margin = 150
