source = ./env.conf
source = ./plugins.conf
source = ./execs.conf

# MONITOR CONFIG
monitor = DP-1, 1920x1080@60, 1360x0, 1
monitor = DP-4, preferred, 0x300, 1
# monitor = HDMI-A-1, preferred, auto, 1, mirror, DP-1
monitor = HDMI-A-1, 1920x1080@60, auto, 1

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-4
workspace = 7, monitor:DP-4
workspace = 8, monitor:DP-4
workspace = 9, monitor:DP-4
workspace = 10, monitor:DP-4

cursor {
  default_monitor = DP-1
}

device {
  name = "2.4g-dongle-2"
  kb_layout = us
}

# device {
#   name = "sonix-usb-device-keyboard"
#   kb_layout = br
# }

input {
    # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = br, us
    # kb_variant = , intl
    kb_options = grp:shift_caps_toggle
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 20
    # resolve_binds_by_sym = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
    }

    special_fallthrough = true
}

binds {
    scroll_event_delay = 0
    allow_pin_fullscreen = true
}

general {
    # Gaps and border
    gaps_in = 4
    gaps_out = 5
    gaps_workspaces = 50
    border_size = 2

    # Fallback colors
    col.active_border = rgba(0DB7D4FF)
    col.inactive_border = rgba(31313600)

    resize_on_border = true
    no_focus_fallback = true
    layout = dwindle

    allow_tearing = true # some guy told me tearing might make things smoother idk

    snap {
      enabled = true
      window_gap = 15
      monitor_gap = 30
    }
}

dwindle {
    smart_resizing = false
    preserve_split = true
    # smart_split = true
}

master {
  new_status = inherit
  new_on_top = true
  allow_small_split = false
  orientation = left
  always_keep_position = false
}

decoration {
    rounding = 5

    blur {
      enabled = true
      xray = false
      special = false
      new_optimizations = on
      size = 1
      passes = 4
      brightness = 1
      noise = 0.01
      contrast = 1
    }

    shadow {
      enabled = true
      range = 25
      ignore_window = true
      offset = 0 2
      render_power = 2
      color = rgba(0000001A)
    }

    # Dim
    dim_inactive = false
    dim_strength = 0.1
    dim_special = 0
}


misc {
    vfr = 1
    vrr = 1
    focus_on_activate = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = false
    enable_swallow = false
    swallow_regex = (foot|kitty|allacritty|Alacritty)

    middle_click_paste = false

    key_press_enables_dpms = true
    mouse_move_focuses_monitor = true

    disable_hyprland_logo = true
}

source = ./hyprland/rules.conf
source = ./hyprland/animations.conf

# # illogical-impulse
# source = ./hyprland/colors.conf
# source = ./illogical-impulse/keybinds.conf

# dms
source = ./dms/binds.conf
source = ./dms/colors.conf
source = ./dms/windowrules.conf

# Keybinds
source = ./hyprland/essential_keybinds.conf
source = ./hyprland/kbptr_keybinds.conf

