#!/bin/bash

DIR="$HOME/.config/rofi"

rofi_command="rofi -theme $DIR/powermenu/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"
_msg="Options  -  yes / y / no / n"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
        ans=$($HOME/.config/rofi/powermenu/confirm)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        gnome-session-quit --power-off --no-prompt
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/powermenu/askpass.rasi -e "$_msg"
        fi
        ;;
    $reboot)
        ans=$($HOME/.config/rofi/powermenu/confirm)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        gnome-session-quit --reboot --no-prompt
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/powermenu/askpass.rasi -e "$_msg"
        fi
        ;;
    $lock)
        dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
        ;;
    $suspend)
        ans=$($HOME/.config/rofi/powermenu/confirm)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        mpc -q pause
        amixer set Master mute
        betterlockscreen --suspend
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/powermenu/askpass.rasi -e "$_msg"
        fi
        ;;
    $logout)
        ans=$($HOME/.config/rofi/powermenu/confirm)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        gnome-session-quit --logout --no-prompt 
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
        rofi -theme ~/.config/rofi/powermenu/askpass.rasi -e "$_msg"
        fi
        ;;
esac
