;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;;; main colors
;background = #282a36
;background-alt = #20212b 
;background-alt-b = #23252F 
;background-alt-c = #1A1B23
;background-alt-d = #111217
;foreground = #CACACA
;foreground-alt = #CACACA
;;primary = #757575
;primary = #20212b
;red = #ff5555
;;yellow = #f1fa8c
;yellow = #FFEE38

;; Tokyonight colors
background = #24283b
background-alt = #1d2030 
background-alt-b = #171926 
background-alt-c = #151724
background-alt-d = #0f101a
foreground = #c0caf5
foreground-alt = #c0caf5
primary = #20212b
red = #f7768e
yellow = #e0af68

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
