;; ┌──────────────────────────────────────────────────────────────────────────────-----┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█░█░█▀▀░█▀▀░█▀▄░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀ │
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░▀▀█░█▀▀░█▀▄░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█ │
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀ │
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └──────────────────────────────────────────────────────────────────────────────-----┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


[module/pipewire]
type = custom/script
exec = ~/.config/polybar/tokyonight/scripts/pipewire_audio.sh
tail = true
click-middle = exec pavucontrol &
click-right = $TOOLS/cycle-audio-devices.nu sink
click-left = ~/.config/polybar/tokyonight/scripts/pipewire_audio.sh --mute &
scroll-up = ~/.config/polybar/tokyonight/scripts/pipewire_audio.sh --up &
scroll-down = ~/.config/polybar/tokyonight/scripts/pipewire_audio.sh --down &

format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/calendar]
type = custom/script
; label = " "
exec = date +" %H:%M  %a, %d/%m/%Y"
; click-left = $HOME/.config/polybar/tokyonight/scripts/calendar.sh curr
; scroll-up = $HOME/.config/polybar/tokyonight/scripts/calendar.sh next
; scroll-down = $HOME/.config/polybar/tokyonight/scripts/calendar.sh prev
click-left = eww open mainframe --toggle&&eww close disclose 
click-right = onboard

format-background = ${color.background-alt-b}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/updates]
type = custom/script

; Available tokens:
;   %counter%
; Command to be executed (using "/usr/bin/env sh -c [command]")
exec = ~/.config/polybar/tokyonight/scripts/updates.sh

; Conditional command that, if defined, needs to exit successfully
; before the main exec command is invoked.
; Default: ""
;;exec-if = ""

; Will the script output continous content?
; Default: false
tail = true

; Seconds to sleep between updates
; Default: 2 (0 if `tail = true`)
interval = 5

; Available tags:
;   <output> - deprecated
;   <label> (default)
format = <label>
format-prefix = 
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2

; Available tokens:
;   %output%
; Default: %output%
label = %output%

; Available tokens:
;   %counter%
;   %pid%
;
; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c [command]"
click-left = exo-open --launch TerminalEmulator &
click-right = exo-open --launch TerminalEmulator &
;;double-click-left = echo double left %counter%
;;double-click-middle = echo double middle %counter%
;;double-click-right = echo double right %counter%

; Available tokens:
;   %counter%
;   %pid%
;
; "scroll-(up|down)" will be executed using "/usr/bin/env sh -c [command]"
;;scroll-up = echo scroll up %counter%
;;scroll-down = echo scroll down %counter%


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/archdots]
type = custom/script
; exec = bspc query -N -n .hidden.window|wc -l
exec = $HOME/.config/polybar/tokyonight/scripts/archdots-status.sh
interval = 120
format-background = ${color.background}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1
click-left = kitty --class __float__ bash -c "dots sync&&printf "Press Enter"&& read a"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/rclone]
type = custom/script
; exec = bspc query -N -n .hidden.window|wc -l
exec = [ "$(cat $HOME/.rclone_status.txt)" = "error" ] && echo "󰼣"
interval = 60
format-background = ${color.background}
format-foreground = ${color.red}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1
click-left = kitty --class __float__ bash -c "gum confirm 'Do you want to resync with Google Drive' && $TOOLS/rclone-sync.sh --resync; printf 'Press Enter'; read a" 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/scratchpad]
type = custom/script
; exec = bspc query -N -n .hidden.window|wc -l
exec = $HOME/.config/polybar/tokyonight/scripts/bspwm-list-hidden.sh
interval = 3
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1
click-left = $TOOLS/rofi-scratchpad-bspwm.sh 
click-right = swap-desktops.sh next --no-follow

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/duolingo]
type = custom/script
exec = "$HOME/.config/polybar/tokyonight/scripts/duolingo_streak.sh"
interval = 100
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1
click-left = xdg-open 'https://duolingo.com'

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bspwm-monocle]
type = custom/ipc
hook-0 = $HOME/.config/polybar/tokyonight/scripts/bspwm-list-monocle.sh "%pid%"
format = <output>
initial = 0

format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/spotify]
type = custom/script
tail = true
; prefix symbol is shown before the text
format-prefix = ""
format = <label>
exec = ~/.config/polybar/tokyonight/scripts/scroll_spotify_status.sh

click-left = playerctl play-pause
click-right = playerctl next

format-background = ${color.background-alt-c}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/rofication]
type = custom/script
;exec = rofication-status
; exec = out=$(rofication-status);python -c "print(''+'$out'[-9:-7] if int('$out'[-9:-7])==0 else '%{F#FFEE38}'+''+'$out'[-9:-7]+'%{F-}')"
exec = "$HOME/.config/polybar/tokyonight/scripts/notifications-count.sh"
; exec = "$HOME/.config/eww/scripts/notification_logger.zsh normal"
click-left=eww open disclose --toggle&&eww close mainframe; $HOME/.config/eww/scripts/notification_logger.zsh clear_pending 
click-right=dunstctl set-paused toggle
; format-prefix = "  "
; format = <label>
interval = 2
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/launcher]
type = custom/text
content = 

; "content" has the same properties as "format-NAME"
content-background = ${color.background}
content-foreground = ${color.foreground-alt}
content-padding = 4

; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c $COMMAND"
click-left = ~/.config/polybar/tokyonight/scripts/launcher.sh &
;;click-middle = ~/.config/polybar/tokyonight/scripts/launcher-full
click-right = ~/.config/polybar/tokyonight/scripts/color-switch.sh &

; "scroll-(up|down)" will be executed using "/usr/bin/env sh -c $COMMAND"
;;scroll-up = ~/.config/polybar/tokyonight/scripts/launcher.sh &
;;scroll-down = ~/.config/polybar/tokyonight/scripts/color-switch.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = 

content-background = ${color.background}
content-foreground = ${color.foreground-alt}
content-padding = 4

click-left = ~/.config/polybar/tokyonight/scripts/powermenu.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/color-switch]
type = custom/text
content = 

content-background = ${color.background-alt}
content-foreground = ${color.foreground}
content-overline = ${color.background}
content-underline = ${color.background}
content-padding = 2

click-left = ~/.config/polybar/tokyonight/scripts/color-switch.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sep]
type = custom/text
content = |

content-background = ${color.background}
content-foreground = ${color.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/apps]
type = custom/text
content-background = ${color.background-alt}
content-foreground = ${color.foreground}
content-overline = ${color.background}
content-underline = ${color.background}
content-padding = 1

[module/term]
inherit = module/apps
content = 
click-left = termite &
click-middle = urxvt &
click-right = xfce4-terminal &

[module/files]
inherit = module/apps
content = 
click-left = thunar &
click-right = pcmanfm &

[module/browser]
inherit = module/apps
content = 
click-left = firefox &
click-right = chromium &

[module/settings]
inherit = module/apps
content = 
click-left = xfce4-settings-manager &
click-right = lxappearance &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/powermenu]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"
menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = shutdown
menu-0-1-exec = menu-open-2

menu-1-0 = back
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = shutdown
menu-2-0-exec = systemctl poweroff
menu-2-1 = back
menu-2-1-exec = menu-open-0

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>

format = <label-toggle> <menu>
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2

label-open = 
label-close =  

; Optional item separator
; Default: none
label-separator = " | "

;;label-open-foreground = ${color.foreground}
;;label-close-foreground = ${color.background}
;;label-separator-foreground = ${color.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/menu]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"
menu-0-0 = Menu
menu-0-0-exec = ~/.config/polybar/tokyonight/scripts/launcher.sh &
menu-0-1 = Files
menu-0-1-exec = thunar &
menu-0-2 = Terminal
menu-0-2-exec = termite &
menu-0-3 = Browser
menu-0-3-exec = firefox &

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>

format = <label-toggle> <menu>
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 2

label-open = 
label-close = 

; Optional item separator
; Default: none
label-separator = " | "

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
