#!/bin/env bash

status_file="/tmp/bspdragwindow_dragging"

[ "$1" = stop ] && {
    [ -e "$status_file" ] \
        && rm -r "$status_file"
    exit
}

[ -e "$status_file" ] \
    && exit

wid=$(bspc query -N -n pointed.floating) \
    || exit

eval "$(xdotool getmouselocation --shell)"
x=$X y=$Y
touch "$status_file"
while [ -e "$status_file" ]; do
    eval "$(xdotool getmouselocation --shell)"
    (( X != x || Y != y )) && {
        [ -n "$(bspc query -N -n .focused.tiled)" ] && exit
        bspc node "$wid" -v "$((X - x))" "$((Y - y))"
        x=$X y=$Y
        sleep .1
    }
done

[ -e "$status_file" ] \
    && rm -r "$status_file"
