#!/usr/bin/env bash

layout_pdm() {
    PYPROJECT_TOML="${PYPROJECT_TOML:-pyproject.toml}"
    if [ ! -f "$PYPROJECT_TOML" ]; then
        log_status "No pyproject.toml found. Executing \`pmd init\` to create a \`$PYPROJECT_TOML\` first."
        pdm init --non-interactive --python "$(python3 --version 2>/dev/null | cut -d' ' -f2 | cut -d. -f1-2)"
    fi

    VIRTUAL_ENV=$(pdm venv list| grep "^*"| sed 's/.*: *//'|head -n1)


    if [ -z "$VIRTUAL_ENV" ] || [ ! -d "$VIRTUAL_ENV" ]; then
        log_status "No virtual environment exists. Executing \`pdm venv create\` to create one."
        pdm venv create
        VIRTUAL_ENV=$(pdm venv list| grep "^*"| sed 's/.*: *//')
    fi
    # PYPACKAGES=$(pdm info| grep '__pypackages__'|xargs)

    # PATH_add "$PYPACKAGES/bin"
    PATH_add "$VIRTUAL_ENV/bin"
    export PDM_ACTIVE=1
    export VIRTUAL_ENV
}


layout_gitpull() {
    git pull
}
